# Generated by Django 6.0.2 on 2026-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial_module1job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module1job',
            name='job_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('policy_upr', 'Policy UPR'), ('update_reserve', 'Update Reserve'), ('uw_parameters', 'UW Parameters')], max_length=32),
        ),
    ]
