# Generated by Django 6.0.4 on 2026-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_chaining_retention_lineage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module1job',
            name='job_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('policy_upr', 'Policy UPR'), ('update_reserve', 'Update Reserve'), ('uw_parameters', 'UW Parameters'), ('module2_allocate', 'Module2 Allocate'), ('module2_process', 'Module2 Process'), ('module2_movement', 'IFRS 17 Movement Analysis')], max_length=32),
        ),
    ]
