# Generated by Django 6.0.4 on 2026-07-07 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_alter_module1job_job_type'),
        ('tenants', '0002_default_output_retention_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('summary', 'Reserve Summary'), ('update_reserve', 'Update Reserves'), ('ibnr_allocation', 'Cash Flow Allocation'), ('movement', 'Movement Analysis')], max_length=32)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_drafts', to='tenants.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'user', 'key'], name='jobdraft_scope_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization', 'key'), name='uniq_job_draft_user_org_key')],
            },
        ),
    ]
