# Generated by Django 6.0.4 on 2026-07-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_jobdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='module1job',
            name='input_archive',
            field=models.FileField(blank=True, null=True, upload_to='module1_jobs/inputs/%Y/%m/'),
        ),
    ]
