# Generated by Django 6.0.4 on 2026-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_alter_module1job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdraft',
            name='key',
            field=models.CharField(choices=[('summary', 'Reserve Summary'), ('update_reserve', 'Update Reserves'), ('ibnr_allocation', 'Cash Flow Allocation'), ('movement', 'Movement Analysis'), ('sensitivity', 'Sensitivity Analysis')], max_length=32),
        ),
    ]
