# Generated by Django 6.0.4 on 2026-09-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_alter_jobdraft_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='module1job',
            name='output_sheets',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
