# Generated by Django 6.0.4 on 2026-09-09 17:52

import core.jsonsafe
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_module1job_output_sheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module1job',
            name='input_meta',
            field=core.jsonsafe.SafeJSONField(blank=True, default=dict),
        ),
    ]
