# Generated by Django 6.0.4 on 2026-08-21 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_default_output_retention_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenario_sets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_sets', to='tenants.organization')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64)),
                ('lever', models.CharField(choices=[('ra', 'Risk adjustment'), ('discount', 'Discount curve'), ('ulr', 'Loss ratio')], max_length=16)),
                ('magnitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('scope_classes', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scenario_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='tenants.scenarioset')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='scenarioset',
            index=models.Index(fields=['organization', 'is_active'], name='scenarioset_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenarioset',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'version'), name='uniq_scenario_set_version'),
        ),
        migrations.AddConstraint(
            model_name='scenarioset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'name'), name='uniq_active_scenario_set_per_name'),
        ),
    ]
