# Generated by Django 6.0.4 on 2026-08-31 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_scenarioset_scenario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UprMethodPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_upr_policies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upr_policies', to='tenants.organization')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='UprMethodRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserving_class', models.CharField(blank=True, max_length=128)),
                ('product_type', models.CharField(blank=True, max_length=128)),
                ('match_mode', models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('prefix', 'Starts with')], default='exact', max_length=16)),
                ('method', models.CharField(max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tenants.uprmethodpolicy')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='uprmethodpolicy',
            index=models.Index(fields=['organization', 'is_active'], name='uprpolicy_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='uprmethodpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'version'), name='uniq_upr_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='uprmethodpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization', 'name'), name='uniq_active_upr_policy_per_name'),
        ),
    ]
