# Generated by Django 6.0.4 on 2026-09-02 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_uprmethodpolicy_uprmethodrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='preflight_mode',
            field=models.CharField(choices=[('strict', 'Strict — block a run with reconciliation errors'), ('permissive', 'Permissive — warn but run anyway')], default='strict', help_text='Strict blocks a reserving run whose claims and premium classes do not reconcile. Permissive runs anyway and records the report.', max_length=16),
        ),
        migrations.CreateModel(
            name='ReservingClassAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=128)),
                ('canonical', models.CharField(max_length=128)),
                ('alias_key', models.CharField(db_index=True, editable=False, max_length=128)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_aliases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserving_class_aliases', to='tenants.organization')),
            ],
            options={
                'ordering': ['canonical', 'alias'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'alias_key'), name='uniq_class_alias_per_org')],
            },
        ),
    ]
