"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, True))
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure--xoxe4!yky(^&#d$$w8=m&c$0qr%(5k8td2e9#*7!tjlh08k0!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '0.0.0.0', 'api.sigma17.leadrisks.com', "sigma17.netlify.app", "sigma17.vercel.app"])

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'tenants',
    'accounts',
    'processing',
    'datasets',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default=f"postgres://{env('DB_USER', default='postgres')}:{env('DB_PASSWORD', default='postgres')}@{env('DB_HOST', default='localhost')}:{env('DB_PORT', default='5432')}/{env('DB_NAME', default='sigma17')}"
    )
}

# Reuse Postgres connections instead of opening a fresh one per request/task.
# Celery tasks are short-lived per job but run many DB statements; CONN_MAX_AGE=0
# (the Django default) forced a new TCP+auth handshake every time. Health checks
# guard against handing out a connection the server already dropped.
# Behind PgBouncer set DB_CONN_MAX_AGE=0 and let the pooler manage lifetimes.
DATABASES['default']['CONN_MAX_AGE'] = env.int('DB_CONN_MAX_AGE', default=600)
DATABASES['default']['CONN_HEALTH_CHECKS'] = env.bool('DB_CONN_HEALTH_CHECKS', default=True)

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': env('DB_NAME', default='sigma17'),
#         'USER': env('DB_USER', default='postgres'),
#         'PASSWORD': env('DB_PASSWORD', default='postgres'),
#         'HOST': env('DB_HOST', default='localhost'),
#         'PORT': env('DB_PORT', default='5432'),
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 60  # 1 hour hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 55 * 60

# --- Worker behaviour tuning (see docs/PERFORMANCE_OPTIMIZATION_PLAN.md §3.2) ---
# prefetch=1: heavy actuarial jobs are long and uneven; the default prefetch of
# 4 lets one worker hoard several big jobs while others idle. One-at-a-time gives
# fair distribution and predictable queue lag.
CELERY_WORKER_PREFETCH_MULTIPLIER = env.int('CELERY_WORKER_PREFETCH_MULTIPLIER', default=1)
# acks_late: a job is re-queued if the worker is killed mid-run (OOM, deploy)
# rather than silently lost. Engine tasks are effectively idempotent — they fully
# rebuild their output dir each run — so redelivery is safe.
CELERY_TASK_ACKS_LATE = env.bool('CELERY_TASK_ACKS_LATE', default=True)
CELERY_TASK_REJECT_ON_WORKER_LOST = env.bool('CELERY_TASK_REJECT_ON_WORKER_LOST', default=True)
# Recycle workers periodically so pandas/openpyxl heap fragmentation can't grow
# unbounded across many large jobs.
CELERY_WORKER_MAX_TASKS_PER_CHILD = env.int('CELERY_WORKER_MAX_TASKS_PER_CHILD', default=50)
CELERY_WORKER_MAX_MEMORY_PER_CHILD = env.int('CELERY_WORKER_MAX_MEMORY_PER_CHILD', default=0) or None
CELERY_TASK_DEFAULT_QUEUE = 'default'
# Route the long compute jobs to a dedicated 'compute' queue so a burst of big
# jobs can't starve light/quick work (status side-effects, retention sweeps).
# Run a worker per queue, e.g.:
#   celery -A config worker -Q compute -c 4 -n compute@%h
#   celery -A config worker -Q default,retention -c 2 -n default@%h
CELERY_TASK_ROUTES = {
    'processing.tasks.run_module1_summary_task': {'queue': 'compute'},
    'processing.tasks.run_module1_policy_upr_task': {'queue': 'compute'},
    'processing.tasks.run_module1_update_reserve_task': {'queue': 'compute'},
    'processing.tasks.run_module1_uw_parameters_task': {'queue': 'compute'},
    'processing.tasks.run_module2_allocate_task': {'queue': 'compute'},
    'processing.tasks.run_module2_process_task': {'queue': 'compute'},
    'processing.tasks.run_module2_movement_task': {'queue': 'compute'},
    'processing.tasks.purge_expired_outputs_task': {'queue': 'retention'},
    'processing.tasks.cascade_purge_task': {'queue': 'retention'},
    'processing.tasks.reap_stuck_jobs_task': {'queue': 'retention'},
}

# Module 1 job uploads (count / size guardrails)
MODULE1_MAX_UPLOAD_FILES = env.int('MODULE1_MAX_UPLOAD_FILES', default=50)
MODULE1_MAX_UPLOAD_MB = env.int('MODULE1_MAX_UPLOAD_MB', default=200)
MODULE1_OUTPUT_PREVIEW_DEFAULT_PAGE_SIZE = env.int(
    'MODULE1_OUTPUT_PREVIEW_DEFAULT_PAGE_SIZE',
    default=50,
)
MODULE1_OUTPUT_PREVIEW_MAX_PAGE_SIZE = env.int(
    'MODULE1_OUTPUT_PREVIEW_MAX_PAGE_SIZE',
    default=200,
)
MODULE1_OUTPUT_PREVIEW_MAX_CELLS = env.int(
    'MODULE1_OUTPUT_PREVIEW_MAX_CELLS',
    default=20000,
)

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require auth by default
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Every error response is normalized to JSON {detail, code, fieldErrors}.
    'EXCEPTION_HANDLER': 'core.exceptions.api_exception_handler',
}

# Logging: API errors must land in the container logs with a correlation id.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'sigma17.api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=DEBUG)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://localhost:5173',
    'http://localhost:8080',
    'https://sigma17.leadrisks.com',
    "https://www.sigma17.leadrisks.com",
    "https://sigma17.netlify.app",
    "https://sigma17.vercel.app",
])

# Allow the tenant-context header to come through CORS
CORS_ALLOW_HEADERS = list(__import__('corsheaders.defaults', fromlist=['default_headers']).default_headers) + [
    'x-organization-id',
]

# Security settings for production
if not DEBUG:
    IS_TESTING = "test" in sys.argv
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Keep these configurable per host/proxy topology.
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not IS_TESTING)
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True
    )
    SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=True)
    SECURE_REFERRER_POLICY = env(
        'SECURE_REFERRER_POLICY', default='same-origin'
    )
    SECURE_CONTENT_TYPE_NOSNIFF = env.bool(
        'SECURE_CONTENT_TYPE_NOSNIFF', default=True
    )
    X_FRAME_OPTIONS = env('X_FRAME_OPTIONS', default='DENY')
    CSRF_TRUSTED_ORIGINS = env.list(
        'CSRF_TRUSTED_ORIGINS',
        default=[
            'https://sigma17.leadrisks.com',
            'https://www.sigma17.leadrisks.com',
            'https://sigma17.netlify.app',
            'https://sigma17.vercel.app',
        ],
    )

