"""Generate the frontend movement schema mirror (schema.ts) from schema.py.

Single source of truth is module2_engine/movement/schema_source.json (+ curated
overrides in schema.py). This emits the TypeScript the dashboard renders from, so the
disclosure layout (rows, indents, sign column, subtotal styling, buckets) can never
drift from the backend. CI should run this and fail on a diff.

Run: python scripts/gen_movement_schema.py
"""

import json
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND))

from module2_engine.movement.schema import SCHEMA, SCHEMA_VERSION  # noqa: E402

OUT = BACKEND.parent / "sigma-17-dashboard" / "src" / "features" / "movement" / "schema.ts"


def to_ts() -> str:
    sheets_obj = {}
    for name, sheet in SCHEMA.sheets.items():
        sheets_obj[name] = {
            "name": name,
            "buckets": list(sheet.buckets),
            "valueBuckets": list(sheet.value_buckets),
            "lines": [
                {
                    "id": ln.id,
                    "row": ln.row,
                    "label": ln.label,
                    "level": ln.level,
                    "kind": ln.kind,
                    "signs": ln.signs,
                }
                for ln in sheet.lines
            ],
        }
    body = json.dumps(sheets_obj, indent=2, ensure_ascii=False)
    return f"""// AUTO-GENERATED by sigma-17-backend/scripts/gen_movement_schema.py — DO NOT EDIT.
// Source of truth: module2_engine/movement/schema_source.json (+ schema.py overrides).
// Regenerate after any schema change; CI fails on drift.

export const MOVEMENT_SCHEMA_VERSION = "{SCHEMA_VERSION}";

export type MovementLineKind =
  | "opening"
  | "input"
  | "subtotal"
  | "closing"
  | "section";

export interface MovementLine {{
  id: string;
  row: number;
  label: string;
  level: number;
  kind: MovementLineKind;
  /** bucket key -> "+" | "-" | "+/-" | "-/+" (input/opening lines) */
  signs: Record<string, string>;
}}

export interface MovementSheet {{
  name: string;
  buckets: string[];
  valueBuckets: string[];
  lines: MovementLine[];
}}

export type MovementSheetName = "Gross" | "RI";

export const MOVEMENT_SCHEMA: Record<MovementSheetName, MovementSheet> =
{body} as const;
"""


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(to_ts(), encoding="utf-8")
    total = sum(len(s.lines) for s in SCHEMA.sheets.values())
    print(f"wrote {OUT}  (v{SCHEMA.version}, {total} lines across {len(SCHEMA.sheets)} sheets)")


if __name__ == "__main__":
    main()
